name: Test Ruby Gem

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Run Rubocop
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Run tests
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
