name: Test Ruby Gem

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 3.2.x
    - name: Run Rubocop
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rubocop

  reek:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 3.2.x
    - name: Run Reek
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec reek

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 3.2.x
    - name: Run tests
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
